version: '3.9'
services:
  postgres:
    image: postgis/postgis:16-3.4
    container_name: arip-postgres
    environment:
      POSTGRES_USER: arip
      POSTGRES_PASSWORD: arip
      POSTGRES_DB: arip
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U arip -d arip"]
      interval: 5s
      timeout: 5s
      retries: 20
volumes:
  pgdata:
